### PR TITLE
feat: update terraform SDK to 0.12.0

### PR DESCRIPTION
**Pull request by QuentinBrosse**
This PR updates the terraform SDK to make this provider compatible with the new [`terraform v0.12.0`](https://github.com/hashicorp/terraform/releases/tag/v0.12.0). This upgrade doesn't introduce breaking changes.

Fix https://github.com/terraform-providers/terraform-provider-scaleway/issues/124

## Upgrading to Terraform v0.12

> For most users, upgrading configuration should be completely automatic. Some simple configurations will require no changes at all, and most other configurations can be prepared by running [the automatic upgrade tool](https://www.terraform.io/docs/commands/0.12upgrade.html). Please read on for more information and recommendations on the upgrade process.

Please, check out the complete terraform guide [here](https://www.terraform.io/upgrade-guides/0-12.html).

## Steps to check this PR

1. Download `terraform 0.12.0`
```bash
$> terraform --version

Terraform v0.12.0
```
2. Set terraform version in the config file:
```tf
terraform {
  required_version = "~> 0.12"
}

```
3. Build provider:
```bash
make build
```

4. Init terraform with a custom `plugin-dir`:
```bash
./terraform init -plugin-dir=$HOME/go/bin

# Output

Initializing the backend...

Initializing provider plugins...

Terraform has been successfully initialized!
[...]
```

5. Run tests
```bash
make test
```

6. Run acceptance tests **WARN: This operation cost money**
```bash
make testacc
```

### CODE REVIEW

**Comment by nicolai86** [comment]
thanks for this, @QuentinBrosse !

**Comment by QuentinBrosse** [comment]
The `v0.12.0` just came out (11h hours ago when I write this comment). I propose to update this PR, is it ok for you @nicolai86?

**Comment by nicolai86** [comment]
Of course!

**Comment by QuentinBrosse** [comment]
I suggest you this command to see the diff without all the vendors:
```bash
git diff cf9abef1b26cab1608d39faa38791f7c1b12cdf6 -- . ':!vendor'
```

**Comment by nicolai86** [comment]
Thanks for the hard work in this! I’ll take another look today!

**Pull request merged**
