### PR TITLE
add user_data support

### PR DESCRIPTION
**Pull request by smola**
Add support for user_data on scaleway_server resources.
On server creation, user_data is created after creating the server and before starting it up, so that it is available on first boot.

### CODE REVIEW

**Comment by smola** [comment]
Note that it passes the new acceptance test, but I'm still testing this on a real deployment to verify, it might have some rough edges.

**Comment by nicolai86** [comment]
Thank you for your contribution, @smola 🎉

Looks good so far. Please update the server documentation to include the new attribute.

**Comment by smola** [comment]
@nicolai86 Updated. I have been using it in my deployment with no issues so far.

**Comment by nicolai86** [comment]
Thank you smola. I’ll take another look today.

**Comment by nicolai86** [comment]
Looks good to me - I’ll run the acceptance tests and move this contribution forward when they pass. Thank you!

**Comment by nicolai86** [comment]
@smola the tests fail with your change, so I can't merge this. please investigate.

`make testacc` passes on master, but with your branch I consistently get errors:

```
make testacc
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test $(go list ./... |grep -v 'vendor') -v  -timeout 120m
?   	github.com/terraform-providers/terraform-provider-scaleway	[no test files]
=== RUN   TestAccScalewayDataSourceBootscript_Filtered
--- PASS: TestAccScalewayDataSourceBootscript_Filtered (5.07s)
=== RUN   TestAccScalewayDataSourceImage_Basic
--- PASS: TestAccScalewayDataSourceImage_Basic (10.35s)
=== RUN   TestAccScalewayDataSourceImage_Filtered
--- PASS: TestAccScalewayDataSourceImage_Filtered (9.55s)
=== RUN   TestAccScalewayIP_importBasic
--- PASS: TestAccScalewayIP_importBasic (3.04s)
=== RUN   TestAccScalewaySecurityGroup_importBasic
--- PASS: TestAccScalewaySecurityGroup_importBasic (3.59s)
=== RUN   TestAccScalewayServer_importBasic
--- PASS: TestAccScalewayServer_importBasic (127.08s)
=== RUN   TestAccScalewayVolume_importBasic
--- PASS: TestAccScalewayVolume_importBasic (2.39s)
=== RUN   TestProvider
--- PASS: TestProvider (0.00s)
=== RUN   TestProvider_impl
--- PASS: TestProvider_impl (0.00s)
=== RUN   TestAccScalewayIP_Count
--- PASS: TestAccScalewayIP_Count (6.46s)
=== RUN   TestAccScalewayIP_Basic
--- PASS: TestAccScalewayIP_Basic (12.29s)
=== RUN   TestAccScalewaySecurityGroupRule_Basic
--- PASS: TestAccScalewaySecurityGroupRule_Basic (7.68s)
=== RUN   TestAccScalewaySecurityGroupRule_Count
--- FAIL: TestAccScalewaySecurityGroupRule_Count (5.58s)
	testing.go:434: Step 0 error: Error on follow-up refresh: 1 error(s) occurred:

		* scaleway_security_group.base: 1 error(s) occurred:

		* scaleway_security_group.base: scaleway_security_group.base: unexpected end of JSON input
=== RUN   TestAccScalewaySecurityGroup_Basic
--- FAIL: TestAccScalewaySecurityGroup_Basic (0.18s)
	testing.go:434: Step 0 error: Error applying: 1 error(s) occurred:

		* scaleway_security_group.base: 1 error(s) occurred:

		* scaleway_security_group.base: unexpected end of JSON input
=== RUN   TestAccScalewayServer_Basic
--- FAIL: TestAccScalewayServer_Basic (0.95s)
	testing.go:434: Step 0 error: Error applying: 1 error(s) occurred:

		* scaleway_server.base: 1 error(s) occurred:

		* scaleway_server.base: unexpected end of JSON input
	testing.go:494: Error destroying resource! WARNING: Dangling resources
		may exist. The full state and error is shown below.

		Error: Error refreshing: 1 error(s) occurred:

		* scaleway_server.base: 1 error(s) occurred:

		* scaleway_server.base: scaleway_server.base: unexpected end of JSON input

		State: <nil>
=== RUN   TestAccScalewayServer_ExistingIP
--- FAIL: TestAccScalewayServer_ExistingIP (0.18s)
	testing.go:434: Step 0 error: Error applying: 1 error(s) occurred:

		* scaleway_ip.base: 1 error(s) occurred:

		* scaleway_ip.base: unexpected end of JSON input
=== RUN   TestAccScalewayServer_Volumes
--- FAIL: TestAccScalewayServer_Volumes (0.18s)
	testing.go:434: Step 0 error: Error applying: 1 error(s) occurred:

		* scaleway_server.base: 1 error(s) occurred:

		* scaleway_server.base: unexpected end of JSON input
=== RUN   TestAccScalewayServer_SecurityGroup
--- FAIL: TestAccScalewayServer_SecurityGroup (0.84s)
	testing.go:434: Step 0 error: Error applying: 2 error(s) occurred:

		* scaleway_security_group.red: 1 error(s) occurred:

		* scaleway_security_group.red: unexpected end of JSON input
		* scaleway_security_group.blue: 1 error(s) occurred:

		* scaleway_security_group.blue: unexpected end of JSON input
=== RUN   TestAccScalewayServer_UserData
--- FAIL: TestAccScalewayServer_UserData (0.17s)
	testing.go:434: Step 0 error: Error applying: 1 error(s) occurred:

		* scaleway_server.base: 1 error(s) occurred:

		* scaleway_server.base: unexpected end of JSON input
=== RUN   TestAccScalewayVolumeAttachment_Basic
--- FAIL: TestAccScalewayVolumeAttachment_Basic (1.15s)
	testing.go:434: Step 0 error: Error applying: 2 error(s) occurred:

		* scaleway_volume.test: 1 error(s) occurred:

		* scaleway_volume.test: Error Creating volume: "unexpected end of JSON input"
		* scaleway_server.base: 1 error(s) occurred:

		* scaleway_server.base: unexpected end of JSON input
	testing.go:494: Error destroying resource! WARNING: Dangling resources
		may exist. The full state and error is shown below.

		Error: Error refreshing: 1 error(s) occurred:

		* scaleway_server.base: 1 error(s) occurred:

		* scaleway_server.base: scaleway_server.base: unexpected end of JSON input

		State: <nil>
=== RUN   TestAccScalewayVolume_Basic
--- FAIL: TestAccScalewayVolume_Basic (0.18s)
	testing.go:434: Step 0 error: Error applying: 1 error(s) occurred:

		* scaleway_volume.test: 1 error(s) occurred:

		* scaleway_volume.test: Error Creating volume: "unexpected end of JSON input"
FAIL
FAIL	github.com/terraform-providers/terraform-provider-scaleway/scaleway	196.943s
```

**Comment by smola** [comment]
It seems this JSON error is actually a rate limit hit: https://github.com/nicolai86/scaleway-sdk/pull/2

I'm checking if the amount of API requests can be reduced.

**Comment by nicolai86** [comment]
@smola  see `resource_volume_attachment.go` for an example using `resource.Retry` - you could use this to work around the api rate limiting.

**Comment by smola** [comment]
I can reproduce the same problem running `make testacc` without this PR applied. I'm preparing a separate PR to handle it.

**Comment by smola** [comment]
I've just noticed that user_data associated to a server ID survives even when the server is terminated. The PR needs an updated to delete user_data when the server is deleted, so we do not leave garbage behind.

**Comment by smola** [comment]
I got this on one of the tests run:

```
=== RUN   TestAccScalewayServer_SecurityGroup
--- FAIL: TestAccScalewayServer_SecurityGroup (137.92s)
	testing.go:434: Step 1 error: After applying this step and refreshing, the plan was not empty:
		
		DIFF:
		
		UPDATE: scaleway_server.base
		  user_data.%:                     "1" => "0"
		  user_data.ssh-host-fingerprints: "1024 4a:62:19:f5:56:12:05:2e:ba:e1:db:d0:75:9b:0b:6d  root@test (DSA)\n256 18:7c:61:36:4d:c6:62:eb:8a:44:18:4e:8b:ee:f9:0e  root@test (ECDSA)\n256 0c:78:51:94:e0:46:01:cd:c8:63:03:bd:0b:5b:1e:c0  root@test (ED25519)\n2048 4e:3c:44:91:a1:23:90:4f:84:5a:85:f2:ac:9a:3d:5f  root@test (RSA)" => ""
```

Some images (including official ones) use user data to export info themselves. This conflicts with user data management as it is implemented in this PR.

**Comment by nicolai86** [comment]
@smola take a look at the `DiffSuppressFunc` to suppress diffs for these cases where we import remote user data.

**Comment by nicolai86** [comment]
Closing due to inactivity.

**Pull request closed without merging**
