### PR TITLE
support concurrent server creation

### LINKED ISSUE #65: Server creation appears to happen sequentially
### Terraform Version
Terraform v0.11.7
+ provider.scaleway v1.4.1

### Affected Resource(s)
- scaleway_server

### Terraform Configuration Files
[tf.zip](https://github.com/terraform-providers/terraform-provider-scaleway/files/2062095/tf.zip)

### Expected Behavior
Servers are created in parallel

### Actual Behavior
Servers are created synchronously, making `tf apply` mega slow

### Steps to Reproduce
1. `terraform apply`

### PR DESCRIPTION
**Pull request by nicolai86**
instead of blocking for the entire resource creation duration, only
block for the actual call to create/ update the scaleway_server
resource; do not block while polling for the resource state.

this should speed up creating multiple servers considerably.

according to @sieben this should be safe now.

closes #65

### CODE REVIEW

**Comment by nicolai86** [comment]
all tests are green so I'm pulling this in optimistically.

**Comment by meyskens** [comment]
Not sure if related but since this was released i tried to create 3 servers and every time only 1/3 booted the rest set itself to an off state, went back to 1.4.1 and it worked fine. If you prefer i can make a seperate issue for this.

**Comment by nicolai86** [comment]
@meyskens this is most definitively relates. I’m so sorry - can you create a new issue to track this?

**Comment by nicolai86** [comment]
@meyskens if you open a bug please include a template which has this issue - I tried reproducing it locally with this template, but it worked without any issues:

```
provider "scaleway" {}

resource "scaleway_server" "base" {
  name = "test"

  count = 5
  image = "5faef9cd-ea9b-4a63-9171-9e26bec03dbc"
  type  = "C1"
  tags  = ["terraform-test"]
}
```

**Comment by nicolai86** [comment]
after some digging it seems to be related to `scaleway_volume_attachment` usage. investigating further...

**Pull request merged**
