### PR TITLE
Add docs about s3 backend on Scaleway Object Storage

### PR DESCRIPTION
**Pull request by sieben**

### CODE REVIEW

**Comment by sieben** [comment]
@sblaisot done thanks :)

**Comment by nicolai86** [comment]
LGTM

**Comment by sieben** [comment]
@nicolai86 Is it normal that this page is not refreshed with the new content? https://www.terraform.io/docs/providers/scaleway/

**Comment by nicolai86** [comment]
@sieben to my best knowledge it’s generated with each release so it reflects the last release. 

To update it we need a new release.

**Pull request merged**
